/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SgnwRating {
        /**
          * max number of stars
         */
        "maxValue": number;
        /**
          * current number of stars
         */
        "value": number;
    }
    interface SgnwSign {
        /**
          * Formal SignWriting in ASCII (FSW) for sign with optional style string
         */
        "fsw": string;
        /**
          * Style String for sign
         */
        "styling": string;
        /**
          * SignWriting in Unicode (SWU) for sign with optional style string
         */
        "swu": string;
    }
    interface SgnwSignbox {
    }
    interface SgnwSymbol {
        /**
          * Formal SignWriting in ASCII (FSW) for symbol with optional style string
         */
        "fsw": string;
        /**
          * ISWA 2010 ID
         */
        "iid": number;
        /**
          * Style String for symbol
         */
        "styling": string;
        /**
          * SignWriting in Unicode (SWU) for symbol with optional style string
         */
        "swu": string;
    }
    interface SgnwUni8String {
        /**
          * SignWriting in Unicode 8 (uni8) for symbol
         */
        "uni": string;
    }
    interface SgnwUni8Symbol {
        /**
          * SignWriting in Unicode 8 (uni8) for symbol
         */
        "uni": string;
    }
}
declare global {
    interface HTMLSgnwRatingElement extends Components.SgnwRating, HTMLStencilElement {
    }
    var HTMLSgnwRatingElement: {
        prototype: HTMLSgnwRatingElement;
        new (): HTMLSgnwRatingElement;
    };
    interface HTMLSgnwSignElement extends Components.SgnwSign, HTMLStencilElement {
    }
    var HTMLSgnwSignElement: {
        prototype: HTMLSgnwSignElement;
        new (): HTMLSgnwSignElement;
    };
    interface HTMLSgnwSignboxElement extends Components.SgnwSignbox, HTMLStencilElement {
    }
    var HTMLSgnwSignboxElement: {
        prototype: HTMLSgnwSignboxElement;
        new (): HTMLSgnwSignboxElement;
    };
    interface HTMLSgnwSymbolElement extends Components.SgnwSymbol, HTMLStencilElement {
    }
    var HTMLSgnwSymbolElement: {
        prototype: HTMLSgnwSymbolElement;
        new (): HTMLSgnwSymbolElement;
    };
    interface HTMLSgnwUni8StringElement extends Components.SgnwUni8String, HTMLStencilElement {
    }
    var HTMLSgnwUni8StringElement: {
        prototype: HTMLSgnwUni8StringElement;
        new (): HTMLSgnwUni8StringElement;
    };
    interface HTMLSgnwUni8SymbolElement extends Components.SgnwUni8Symbol, HTMLStencilElement {
    }
    var HTMLSgnwUni8SymbolElement: {
        prototype: HTMLSgnwUni8SymbolElement;
        new (): HTMLSgnwUni8SymbolElement;
    };
    interface HTMLElementTagNameMap {
        "sgnw-rating": HTMLSgnwRatingElement;
        "sgnw-sign": HTMLSgnwSignElement;
        "sgnw-signbox": HTMLSgnwSignboxElement;
        "sgnw-symbol": HTMLSgnwSymbolElement;
        "sgnw-uni8-string": HTMLSgnwUni8StringElement;
        "sgnw-uni8-symbol": HTMLSgnwUni8SymbolElement;
    }
}
declare namespace LocalJSX {
    interface SgnwRating {
        /**
          * max number of stars
         */
        "maxValue"?: number;
        /**
          * number of stars was updated
         */
        "onRatingUpdated"?: (event: CustomEvent<any>) => void;
        /**
          * current number of stars
         */
        "value"?: number;
    }
    interface SgnwSign {
        /**
          * Formal SignWriting in ASCII (FSW) for sign with optional style string
         */
        "fsw"?: string;
        /**
          * Style String for sign
         */
        "styling"?: string;
        /**
          * SignWriting in Unicode (SWU) for sign with optional style string
         */
        "swu"?: string;
    }
    interface SgnwSignbox {
    }
    interface SgnwSymbol {
        /**
          * Formal SignWriting in ASCII (FSW) for symbol with optional style string
         */
        "fsw"?: string;
        /**
          * ISWA 2010 ID
         */
        "iid"?: number;
        /**
          * Style String for symbol
         */
        "styling"?: string;
        /**
          * SignWriting in Unicode (SWU) for symbol with optional style string
         */
        "swu"?: string;
    }
    interface SgnwUni8String {
        /**
          * SignWriting in Unicode 8 (uni8) for symbol
         */
        "uni"?: string;
    }
    interface SgnwUni8Symbol {
        /**
          * SignWriting in Unicode 8 (uni8) for symbol
         */
        "uni"?: string;
    }
    interface IntrinsicElements {
        "sgnw-rating": SgnwRating;
        "sgnw-sign": SgnwSign;
        "sgnw-signbox": SgnwSignbox;
        "sgnw-symbol": SgnwSymbol;
        "sgnw-uni8-string": SgnwUni8String;
        "sgnw-uni8-symbol": SgnwUni8Symbol;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sgnw-rating": LocalJSX.SgnwRating & JSXBase.HTMLAttributes<HTMLSgnwRatingElement>;
            "sgnw-sign": LocalJSX.SgnwSign & JSXBase.HTMLAttributes<HTMLSgnwSignElement>;
            "sgnw-signbox": LocalJSX.SgnwSignbox & JSXBase.HTMLAttributes<HTMLSgnwSignboxElement>;
            "sgnw-symbol": LocalJSX.SgnwSymbol & JSXBase.HTMLAttributes<HTMLSgnwSymbolElement>;
            "sgnw-uni8-string": LocalJSX.SgnwUni8String & JSXBase.HTMLAttributes<HTMLSgnwUni8StringElement>;
            "sgnw-uni8-symbol": LocalJSX.SgnwUni8Symbol & JSXBase.HTMLAttributes<HTMLSgnwUni8SymbolElement>;
        }
    }
}
