/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FswSign {
        /**
          * FSW string for sign
         */
        "sign": string;
        /**
          * Style String for sign
         */
        "styling": string;
    }
    interface FswSymbol {
        /**
          * Style String for symbol
         */
        "styling": string;
        /**
          * FSW character for symbol
         */
        "symbol": string;
    }
    interface FswVp {
        /**
          * FSW text
         */
        "vp": string;
    }
    interface SgnwSign {
        /**
          * SWU string for sign
         */
        "sign": string;
        /**
          * Style String for sign
         */
        "styling": string;
    }
    interface SgnwSymbol {
        /**
          * Style String for symbol
         */
        "styling": string;
        /**
          * SWU character for symbol
         */
        "symbol": string;
    }
}
declare global {
    interface HTMLFswSignElement extends Components.FswSign, HTMLStencilElement {
    }
    var HTMLFswSignElement: {
        prototype: HTMLFswSignElement;
        new (): HTMLFswSignElement;
    };
    interface HTMLFswSymbolElement extends Components.FswSymbol, HTMLStencilElement {
    }
    var HTMLFswSymbolElement: {
        prototype: HTMLFswSymbolElement;
        new (): HTMLFswSymbolElement;
    };
    interface HTMLFswVpElement extends Components.FswVp, HTMLStencilElement {
    }
    var HTMLFswVpElement: {
        prototype: HTMLFswVpElement;
        new (): HTMLFswVpElement;
    };
    interface HTMLSgnwSignElement extends Components.SgnwSign, HTMLStencilElement {
    }
    var HTMLSgnwSignElement: {
        prototype: HTMLSgnwSignElement;
        new (): HTMLSgnwSignElement;
    };
    interface HTMLSgnwSymbolElement extends Components.SgnwSymbol, HTMLStencilElement {
    }
    var HTMLSgnwSymbolElement: {
        prototype: HTMLSgnwSymbolElement;
        new (): HTMLSgnwSymbolElement;
    };
    interface HTMLElementTagNameMap {
        "fsw-sign": HTMLFswSignElement;
        "fsw-symbol": HTMLFswSymbolElement;
        "fsw-vp": HTMLFswVpElement;
        "sgnw-sign": HTMLSgnwSignElement;
        "sgnw-symbol": HTMLSgnwSymbolElement;
    }
}
declare namespace LocalJSX {
    interface FswSign {
        /**
          * FSW string for sign
         */
        "sign"?: string;
        /**
          * Style String for sign
         */
        "styling"?: string;
    }
    interface FswSymbol {
        /**
          * Style String for symbol
         */
        "styling"?: string;
        /**
          * FSW character for symbol
         */
        "symbol"?: string;
    }
    interface FswVp {
        /**
          * FSW text
         */
        "vp"?: string;
    }
    interface SgnwSign {
        /**
          * SWU string for sign
         */
        "sign"?: string;
        /**
          * Style String for sign
         */
        "styling"?: string;
    }
    interface SgnwSymbol {
        /**
          * Style String for symbol
         */
        "styling"?: string;
        /**
          * SWU character for symbol
         */
        "symbol"?: string;
    }
    interface IntrinsicElements {
        "fsw-sign": FswSign;
        "fsw-symbol": FswSymbol;
        "fsw-vp": FswVp;
        "sgnw-sign": SgnwSign;
        "sgnw-symbol": SgnwSymbol;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fsw-sign": LocalJSX.FswSign & JSXBase.HTMLAttributes<HTMLFswSignElement>;
            "fsw-symbol": LocalJSX.FswSymbol & JSXBase.HTMLAttributes<HTMLFswSymbolElement>;
            "fsw-vp": LocalJSX.FswVp & JSXBase.HTMLAttributes<HTMLFswVpElement>;
            "sgnw-sign": LocalJSX.SgnwSign & JSXBase.HTMLAttributes<HTMLSgnwSignElement>;
            "sgnw-symbol": LocalJSX.SgnwSymbol & JSXBase.HTMLAttributes<HTMLSgnwSymbolElement>;
        }
    }
}
